name: workflow_01
on:
  workflow_dispatch:
     inputs:
      workflow_02:
        description: 'Ù‹Workflow 2 which will be triggered'
        required: true
        default: 'workflow_02'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: ':zadeeku'

      workflow2_repo_github:
        description: 'repo-name'
        required: true
        default: ':DOCKER_POC_OS' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/zadeeku/DOCKER_POC_OS/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3
      - name: alternate
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/zadeeku/DOCKER_POC_OS/dispatches \
          -d '{"event_type":"Trigger Workflow","client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      
